### ISSUE TITLE
Clone User Repos with Search Flag?

### ISSUE THREAD

**Issue by pa-0** [BrickBot/gh-archive-org#1]
Is this possible?

**Comment by mesheets** [comment]
GitHub's distinctions between "user" collections of repositories and "organizational" collection of repositories is perhaps a little confusing, but—with some exceptions—their behavior is largely similar.  (An example of one such quirk where a distinction is needed can be seen in the code [here](https://github.com/BrickBot/gh-archive-org/blob/7363e14082a6cfac703de16d7e2f7a6dc0e288ff/gh-archive-org#L249).)  In short, though, this script should work for both "user" (e.g. "poa00") and "org" (e.g. "BrickBot") repository collections.

This includes both [search](https://github.com/BrickBot/gh-archive-org/blob/7363e14082a6cfac703de16d7e2f7a6dc0e288ff/gh-archive-org#L234) and [clone (if not cloned previously) / sync (if cloned previously)](https://github.com/BrickBot/gh-archive-org/blob/7363e14082a6cfac703de16d7e2f7a6dc0e288ff/gh-archive-org#L71) capabilities against the available [upstream remote branches](https://github.com/BrickBot/gh-archive-org/blob/7363e14082a6cfac703de16d7e2f7a6dc0e288ff/gh-archive-org#L114).

If seeking just clone capabilities without the archiving aspects, [gh-clone-org](https://github.com/matt-bartel/gh-clone-org) perhaps might be of interest.  (Like this script, it also includes a search flag option.)

Hope this helps!

**Comment by pa-0** [comment]
Thank you!
